import {KEYS,parseNotes,formatNotes,chordVoicing,validateScore,midiBytes} from './music.js';
import {renderAudio} from './audio.js';
const $=id=>document.getElementById(id);let score,current,config={},imageData,playUrl,imageUrl,busy=false;
const names={verse:'主歌',chorus:'副歌'},mix={melody:1,arpeggio:1,cello:1,violin:1,flute:1};
const label=n=>names[n]||n;
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function invalidate(){if(playUrl){URL.revokeObjectURL(playUrl);playUrl=null;}$('player').pause();$('player').removeAttribute('src');$('player').hidden=true;$('download').hidden=true;}
function changed(){invalidate();try{const v=validateScore(score);$('duration').textContent=`${Math.floor(Math.round(v.seconds)/60)}:${String(Math.round(v.seconds)%60).padStart(2,'0')}`;$('barCount').textContent=`${v.bars} 小節`;status('設定已更新，可以重新試聽。');}catch(e){$('duration').textContent='待修正';status(e.message,true);}$('formChips').replaceChildren(...score.form.map(f=>{const s=document.createElement('span');s.textContent=label(f.section);return s;}));}
function editor(){
 $('sectionTabs').replaceChildren(...Object.keys(score.sections).map(s=>{const b=document.createElement('button');b.textContent=label(s);b.setAttribute('role','tab');b.setAttribute('aria-selected',String(s===current));b.onclick=()=>{current=s;editor();};return b;}));
 $('measures').replaceChildren(...score.sections[current].map((bar,i)=>{
  const row=document.createElement('div');row.className='measure';const n=document.createElement('span');n.textContent=String(i+1).padStart(2,'0');const ch=document.createElement('input');ch.value=bar.chord||'';ch.setAttribute('aria-label',`${label(current)}第 ${i+1} 小節和絃`);const note=document.createElement('input');note.value=formatNotes(bar.notes,score.key);note.setAttribute('aria-label',`${label(current)}第 ${i+1} 小節音符`);const total=document.createElement('span');total.className='beat-total';
  const check=()=>{const sum=bar.notes.reduce((a,n)=>a+n[1],0),expected=bar.beats??score.meter[0]*4/score.meter[1];total.textContent=`${sum}/${expected}`;row.classList.toggle('bad',Math.abs(sum-expected)>.00001);};check();
  note.onchange=()=>{try{bar.notes=parseNotes(note.value,score.key);delete bar._invalid;check();changed();}catch(e){bar._invalid=true;row.classList.add('bad');invalidate();status(e.message,true);}};
  ch.onchange=()=>{try{const symbol=ch.value.trim();const c=chordVoicing(symbol);score.chords??={};score.chords[symbol]=c;bar.chord=symbol;delete bar._chordInvalid;changed();}catch(e){bar._chordInvalid=true;invalidate();status(e.message,true);}};
  row.append(n,ch,note,total);return row;
 }));
}
function installScore(s){validateScore(s);score=structuredClone(s);current=Object.keys(score.sections)[0];$('title').value=score.title||'未命名樂曲';$('key').value=score.key;$('meter').value=score.meter.join('/');$('bpm').value=score.bpm;$('lyrics').value=score.lyrics||'';$('warnings').textContent=(score.warnings||[]).join('\n');const secs=Object.keys(score.sections),first=secs[0];$('repeats').value=score.form.filter(f=>f.section===first).length||1;$('finalChorus').checked=score.form.length%secs.length===1;editor();changed();}
async function example(){if(busy)return;try{const r=await fetch('./example.json');if(!r.ok)throw Error('範例載入失敗');installScore(await r.json());}catch(e){status(e.message,true);}}
function currentScore(){if(!Number.isInteger(Number($('repeats').value))||Number($('repeats').value)<1||Number($('repeats').value)>8)throw Error('遍數請輸入 1–8。');if(Object.values(score.sections).flat().some(b=>b._invalid||b._chordInvalid))throw Error('請先修正標示有誤的音符或和絃。');validateScore(score);return structuredClone(score);}
function form(){const n=Number($('repeats').value);if(!Number.isInteger(n)||n<1||n>8){status('遍數請輸入 1–8。',true);return;}const secs=Object.keys(score.sections);score.form=[];for(let i=0;i<n;i++)for(const s of secs)score.form.push({section:s,intensity:i===0?.85:i===2?.8:1,strings:s==='chorus'||i%2===1,flute:s==='chorus'||i>0});if($('finalChorus').checked){const s=secs.includes('chorus')?'chorus':secs.at(-1);score.form.push({section:s,intensity:1.1,strings:true,flute:true});}changed();}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function safeName(){return (score.title||'score').replace(/[<>:"/\\|?*\x00-\x1F]/g,'_').slice(0,70);}
function lock(value){busy=value;for(const el of document.querySelectorAll('input,select,textarea,button'))el.disabled=value;$('recognize').disabled=value||!imageData||!config.recognitionEndpoint;}
async function render(preview){if(busy)return;try{const s=currentScore(),mode=$('mode').value;lock(true);invalidate();$('progress').hidden=false;const blob=await renderAudio(s,mode,{...mix},preview,(v,t)=>{$('progress').value=v;status(t);});playUrl=URL.createObjectURL(blob);$('player').src=playUrl;$('player').hidden=false;$('download').href=playUrl;$('download').download=safeName()+(preview?'_試聽':'_完整')+'.mp3';$('download').textContent=preview?'下載試聽 MP3':'下載完整 MP3';$('download').hidden=false;$('progress').value=100;status(preview?'前 8 小節已完成。喜歡這個音色，就產生完整版本。':'完整演奏已完成，可以播放或下載。');}catch(e){status(e.message,true);}finally{lock(false);$('progress').hidden=true;}}
for(const [part,title]of Object.entries({melody:'鋼琴旋律',arpeggio:'鋼琴伴奏',cello:'大提琴',violin:'弦樂',flute:'長笛'})){
 const div=document.createElement('div');div.className='channel';const lab=document.createElement('label');lab.htmlFor='mix-'+part;lab.textContent=title;const val=document.createElement('output');val.textContent='100%';const range=document.createElement('input');range.id='mix-'+part;range.type='range';range.min=0;range.max=150;range.value=100;range.oninput=()=>{mix[part]=Number(range.value)/100;val.textContent=range.value+'%';invalidate();};lab.append(val);div.append(lab,range);$('mixer').append(div);
}
$('loadExample').onclick=example;$('title').onchange=()=>{score.title=$('title').value;changed();};$('bpm').onchange=()=>{score.bpm=Number($('bpm').value);changed();};$('meter').onchange=()=>{score.meter=$('meter').value.split('/').map(Number);editor();changed();};
$('key').onchange=()=>{const next=$('key').value;let delta=KEYS[next]-KEYS[score.key];if(delta>6)delta-=12;if(delta<-6)delta+=12;for(const bars of Object.values(score.sections))for(const b of bars)for(const n of b.notes)if(n[0]!==null)n[0]+=delta;
 const old=score.chords||{},chords={};const transposeSymbol=s=>s.replace(/[A-G][b#]?/g,x=>{const pc={...KEYS,'C#':1,'D#':3,'F#':6,'G#':8,'A#':10}[x];return Object.keys(KEYS).find(k=>KEYS[k]===((pc+delta+12)%12))||x;});
 for(const [name,c]of Object.entries(old))chords[transposeSymbol(name)]={bass:c.bass+delta,tones:c.tones.map(p=>p+delta)};for(const bs of Object.values(score.sections))for(const b of bs)if(b.chord)b.chord=transposeSymbol(b.chord);score.chords=chords;score.key=next;editor();changed();};
$('repeats').onchange=form;$('finalChorus').onchange=form;$('mode').onchange=changed;$('lyrics').oninput=()=>{score.lyrics=$('lyrics').value;};$('addBar').onclick=()=>{score.sections[current].push({chord:score.key,notes:[[null,score.meter[0]*4/score.meter[1]]]});editor();changed();};
$('preview').onclick=()=>render(true);$('render').onclick=()=>render(false);$('midi').onclick=()=>{try{download(new Blob([midiBytes(currentScore(),$('mode').value,mix)],{type:'audio/midi'}),safeName()+'.mid');}catch(e){status(e.message,true);}};$('saveJson').onclick=()=>{try{download(new Blob([JSON.stringify(currentScore(),null,2)],{type:'application/json'}),safeName()+'.json');}catch(e){status(e.message,true);}};
$('jsonFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1024*1024)throw Error('樂譜檔案不可超過 1 MB。');installScore(JSON.parse(await f.text()));}catch(e){status(e.message,true);}finally{$('jsonFile').value='';}};
$('imageFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>6*1024*1024)throw Error('請選擇 6 MB 以內的 PNG、JPG 或 WebP 圖片。');if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl=URL.createObjectURL(f);$('scoreImage').src=imageUrl;$('scoreImage').hidden=false;imageData=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});$('recognize').disabled=!config.recognitionEndpoint;status(config.recognitionEndpoint?'圖片已選取。按 AI 讀取後，請核對音符與拍數。':'圖片已載入供對照；網站管理者尚未啟用 AI 讀譜。');}catch(e){imageData=null;$('recognize').disabled=true;status(e.message,true);}};
$('recognize').onclick=async()=>{if(!imageData||!config.recognitionEndpoint||busy)return;try{lock(true);status('AI 正在讀取簡譜，約需 30–90 秒…');const r=await fetch(config.recognitionEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:imageData}),signal:AbortSignal.timeout(120000)});const result=await r.json();if(!r.ok)throw Error(result.error||'讀譜服務暫時無法使用。');installScore(result.score);status('AI 已完成讀譜。請對照圖片核對高低音、拍數與和絃後，再產生演奏。');}catch(e){status(e.name==='TimeoutError'?'讀譜逾時，請稍後重試。':e.message,true);}finally{lock(false);}};
try{config=await(await fetch('./config.json')).json();}catch{}if(!config.recognitionEndpoint)$('aiInfo').textContent='AI 讀譜尚未啟用。你仍可載入圖片對照、匯入 JSON 或編輯音符，並免費產生音樂。';
await example();
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'get_score',description:'Read the current visible score and arrangement settings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({score:currentScore(),mode:$('mode').value,mix})});document.modelContext.registerTool({name:'stage_score',description:'Load a transcribed score into the visible editor for review; does not render, upload or publish.',inputSchema:{type:'object',properties:{score:{type:'object'}},required:['score'],additionalProperties:false},execute:input=>{if(busy)throw Error('Rendering in progress');installScore(input.score);return {title:score.title,...validateScore(score)};}});}
