import {fromTranscription,parseChordChanges,writtenEvents} from './score-bridge.js';
import {wordBlob,parseVerses} from './word-export.js';
import {KEYS,chordVoicing} from './music.js';
export function connectStudio({getScore,installScore,status,download,lock,isBusy}){
 const $=id=>document.getElementById(id);let audioFile,sourceUrl,analysisWorker,chordTimeline=[],generation=0;
 for(const mode of ['Audio','Image','Data'])$('tab'+mode).onclick=()=>{for(const m of ['Audio','Image','Data']){$('source'+m).hidden=m!==mode;$('tab'+m).setAttribute('aria-selected',String(m===mode));}};
 $('audioFile').onchange=e=>{audioFile=e.target.files[0];if(!audioFile)return;if(audioFile.size>20*1024*1024){audioFile=null;$('analysisStatus').textContent='請選擇 20 MB 以內的音訊。';return;}if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(audioFile);$('sourcePlayer').src=sourceUrl;$('sourcePlayer').hidden=false;$('audioName').textContent=audioFile.name;$('analyze').disabled=false;};
 $('analysisMode').onchange=()=>{$('analyze').textContent=$('analysisMode').value==='chords'?'估計伴奏和弦':'辨識旋律';};
 const done=()=>{lock(false);$('analyze').disabled=!audioFile;$('cancelAnalysis').hidden=true;$('analysisProgress').hidden=true;analysisWorker=null;};
 $('cancelAnalysis').onclick=()=>{generation++;analysisWorker?.terminate();done();$('analysisStatus').textContent='分析已取消，原樂譜保留。';};
 $('analyze').onclick=async()=>{if(!audioFile||isBusy())return;const operation=++generation;try{lock(true);$('cancelAnalysis').hidden=false;$('cancelAnalysis').disabled=false;$('analysisProgress').hidden=false;$('analysisProgress').value=0;$('analysisStatus').textContent='正在解碼音訊，檔案不會上傳…';const context=new AudioContext();let decoded;try{decoded=await context.decodeAudioData(await audioFile.arrayBuffer());}finally{await context.close();}if(decoded.duration>180)throw Error('請使用 3 分鐘內的音訊片段。');
 const sr=8000,offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*sr),sr),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();const samples=(await offline.startRendering()).getChannelData(0);if(operation!==generation)return;const mode=$('analysisMode').value,bpm=Number($('sourceBpm').value)||0;if(mode==='chords'&&!bpm)throw Error('伴奏和弦估計請先輸入 BPM，以決定分析區間。');
 analysisWorker=new Worker(new URL('./analysis-worker.js',import.meta.url),{type:'module'});$('analysisStatus').textContent=mode==='chords'?'正在分析和弦，請保留此頁面…':'正在辨識音高與節奏，請保留此頁面…';analysisWorker.onerror=()=>{$('analysisStatus').textContent='分析中斷，請改用較短錄音。';analysisWorker?.terminate();done();};
 analysisWorker.onmessage=({data})=>{if(data.progress!==undefined){$('analysisProgress').value=data.progress*100;return;}try{if(data.error)throw Error(data.error);if(mode==='chords'){chordTimeline=data.result;$('chordTimeline').textContent=chordTimeline.map(c=>`${c.time.toFixed(2)} s　${c.text}`).join('\n');$('chordResults').hidden=false;$('analysisStatus').textContent='和弦估計完成，尚未覆蓋樂譜。請確認起點、速度及調性後套用。';}else{const s=fromTranscription(data.result);installScore(s);$('mode').value='melody';$('analysisStatus').textContent='旋律校對稿已載入。請先試聽，校正長音、休止與弱起，再加入歌詞。';status('單音辨識完成，請逐小節核對。');}}catch(e){$('analysisStatus').textContent=e.message;}finally{analysisWorker?.terminate();done();}};
 analysisWorker.postMessage({samples,sampleRate:sr,mode,options:{key:$('sourceKey').value,bpm,pickup:Number($('pickup').value),title:audioFile.name.replace(/\.[^.]+$/,'')}},[samples.buffer]);
 }catch(e){if(operation===generation){$('analysisStatus').textContent=e.message;done();}}};
 $('exportWord').onclick=()=>{try{const s=getScore();download(wordBlob(s),(s.title||'詞譜')+'_A4.docx');status('Word 已產生。請用安裝 01SMN 與標楷體的 Word 開啟；長譜可能分頁。');}catch(e){status(e.message,true);}};
 $('lyricFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error('歌詞檔請小於 100 KB。');let text=(await f.text()).replace(/^\uFEFF/,'');const s=getScore();if(text.trimStart().startsWith(s.title+'\n')||text.trimStart().startsWith(s.title+'\r\n'))text=text.trimStart().slice(s.title.length).trimStart();s.lyrics=text;installScore(s);updateCount();}catch(e){status(e.message,true);}finally{e.target.value='';}};
 function updateCount(){try{const s=getScore(),count=writtenEvents(s).events.filter(e=>e.midi!==null).length,verses=parseVerses(s.lyrics);$('lyricCount').textContent=`${count} 個起音`+(verses.length?` · ${verses.length} 節歌詞 · 各節 ${verses.map(v=>v.length).join('／')} 字`:' · 尚未加入歌詞');}catch{}}
 $('lyrics').addEventListener('input',updateCount);document.addEventListener('scorechange',updateCount);
 $('suggestChords').onclick=()=>{try{const s=getScore(),candidates=[0,2,4,5,7,9,11].map((interval,i)=>Object.keys(KEYS).find(k=>KEYS[k]===(KEYS[s.key]+interval)%12)+['','m','m','','','m','dim'][i]);candidates.push(Object.keys(KEYS).find(k=>KEYS[k]===(KEYS[s.key]+7)%12)+'7');for(const bars of Object.values(s.sections))for(const b of bars){if(b.chord||b.chordChanges?.length)continue;let best={score:-Infinity,text:s.key};for(const symbol of candidates){const c=chordVoicing(symbol),pcs=c.tones.map(p=>p%12);let value=0;for(const [p,d]of b.notes)if(p!==null)value+=d*(pcs.includes(p%12)?1:-.6);if(symbol===s.key)value+=.1;if(value>best.score)best={score:value,text:symbol};}b.chord=best.text;b.chordChanges=[{beat:0,text:best.text}];s.chords[best.text]=chordVoicing(best.text);}s.warnings=[...(s.warnings||[]),'和弦為根據旋律的建議編配，非錄音伴奏辨識。'];installScore(s);status('已為空白小節加入建議和弦，原有和弦保留。請試奏校對。');}catch(e){status(e.message,true);}};
 $('saveChords').onclick=()=>download(new Blob([JSON.stringify({method:'browser-chroma-template-experimental',bpm:Number($('sourceBpm').value),chords:chordTimeline},null,2)],{type:'application/json'}),'和弦時間表.json');
 $('applyChords').onclick=()=>{try{const s=getScore(),offset=Number($('alignmentOffset').value);if(!Number.isFinite(offset)||offset<0)throw Error('請填入正確錄音起點。');if(s.key!==$('sourceKey').value||s.bpm!==Number($('sourceBpm').value))throw Error('請先將樂譜調性及 BPM 設為與錄音一致。');let at=0;for(const bars of Object.values(s.sections))for(const b of bars){const length=b.notes.reduce((n,x)=>n+x[1],0),a=offset+at*60/s.bpm,z=offset+(at+length)*60/s.bpm;const held=chordTimeline.filter(c=>c.time<=a).at(-1);const cs=[...(held?[{time:a,text:held.text}]:[]),...chordTimeline.filter(c=>c.time>a&&c.time<z)];b.chordChanges=cs.filter(c=>c.text!=='N').map(c=>({beat:(c.time-a)*s.bpm/60,text:c.text}));b.chord=b.chordChanges[0]?.text||'';for(const c of b.chordChanges)s.chords[c.text]=chordVoicing(c.text);at+=length;}s.warnings=[...(s.warnings||[]),'和弦依錄音起點及固定速度對位，尚未驗證反覆與速度變化。'];installScore(s);status('估計和弦已套入，請核對拍點及前奏位置。');}catch(e){status(e.message,true);}};
 return {updateCount};
}
